name: pystimulation
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - aom=3.12.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2026.01.04
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - expat=2.7.4
  - fontconfig=2.15.0
  - fonttools=4.61.0
  - freeglut=3.8.0
  - freetype=2.14.1
  - fribidi=1.0.16
  - graphite2=1.3.14
  - harfbuzz=12.3.0
  - icc_rt=2022.1.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9f
  - kiwisolver=1.4.9
  - lcms2=2.17
  - lerc=4.0.0
  - libavif=1.3.0
  - libdeflate=1.22
  - libexpat=2.7.4
  - libffi=3.4.4
  - libglib=2.86.3
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkrb5=1.22.1
  - libopenjpeg=2.5.4
  - libpng=1.6.54
  - libpq=17.6
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.0.19
  - packaging=25.0
  - pandas=2.1.0
  - pcre2=10.46
  - pillow=12.1.0
  - pip=26.0.1
  - pixman=0.46.4
  - pyparsing=3.2.5
  - pyqt=6.10.2
  - pyqt6-sip=13.11.0
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - qtbase=6.10.2
  - qtdeclarative=6.10.2
  - qtsvg=6.10.2
  - qttools=6.10.2
  - qtwebchannel=6.10.2
  - qtwebsockets=6.10.2
  - scipy=1.11.4
  - setuptools=80.10.2
  - sip=6.15.1
  - six=1.17.0
  - sqlite=3.51.1
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - tk=8.6.15
  - tornado=6.5.4
  - tzdata=2025c
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - astropy==5.3.4
      - asttokens==3.0.1
      - async-lru==2.2.0
      - attrs==25.4.0
      - autobahn==25.12.2
      - babel==2.18.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - cbor2==5.8.0
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - comm==0.2.3
      - cryptography==46.0.5
      - debugpy==1.8.20
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyperlink==21.0.0
      - idna==3.11
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.8.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-proxy==4.4.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - lark==1.3.1
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mistune==3.2.0
      - msgpack==1.1.2
      - multidict==6.7.1
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.5.3
      - notebook-shim==0.2.4
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.6
      - platformdirs==4.9.2
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.2
      - pure-eval==0.2.3
      - py-ubjson==0.16.1
      - pycparser==3.0
      - pyerfa==2.0.1.5
      - pygments==2.19.2
      - python-json-logger==4.0.0
      - pywinpty==3.0.3
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - send2trash==2.1.0
      - simpervisor==1.0.0
      - soupsieve==2.8.3
      - spiceypy==8.0.2
      - stack-data==0.6.3
      - terminado==0.18.1
      - tinycss2==1.4.0
      - traitlets==5.14.3
      - txaio==25.12.2
      - typing-extensions==4.15.0
      - ujson==5.11.0
      - uri-template==1.3.0
      - urllib3==2.6.3
      - vpython==7.6.4
      - wcwidth==0.6.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - yarl==1.22.0

